[package]
name = "backup_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.10.0"
ic-cdk-macros = "0.10.0"
candid = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4.31"